import { defineArrayMember, defineField, defineType } from "sanity";

const imageWithAlt = defineField({
  name: "image",
  title: "Card image",
  description: "Appears as the image for this website card.",
  type: "image",
  options: { hotspot: true },
  fields: [
    defineField({
      name: "alt",
      title: "Alt text",
      description: "Describe the photo for accessibility and SEO.",
      type: "string",
    }),
  ],
});

const sectionFields = [
  defineField({
    name: "introKicker",
    title: "Intro label",
    description: "Small uppercase label above the first section after the hero.",
    type: "string",
  }),
  defineField({
    name: "introHeading",
    title: "Intro heading",
    description: "Large heading in the first section after the hero.",
    type: "string",
  }),
  defineField({
    name: "eventsKicker",
    title: "Events label",
    description: "Small label above the Events section heading.",
    type: "string",
  }),
  defineField({
    name: "eventsHeading",
    title: "Events heading",
    description: "Large heading above the event type cards.",
    type: "string",
  }),
  defineField({
    name: "offersKicker",
    title: "Offers label",
    description: "Small label above the Offers / Services section.",
    type: "string",
  }),
  defineField({
    name: "offersHeading",
    title: "Offers heading",
    description: "Large heading above the service cards.",
    type: "string",
  }),
  defineField({
    name: "offersIntro",
    title: "Offers intro",
    description: "Short paragraph to the right of the Offers heading.",
    type: "text",
  }),
  defineField({
    name: "packagesKicker",
    title: "Packages label",
    description: "Small label above the Featured Packages section.",
    type: "string",
  }),
  defineField({
    name: "packagesHeading",
    title: "Packages heading",
    description: "Large heading above the package cards.",
    type: "string",
  }),
  defineField({
    name: "galleryKicker",
    title: "Gallery label",
    description: "Small label above the Gallery section.",
    type: "string",
  }),
  defineField({
    name: "galleryHeading",
    title: "Gallery heading",
    description: "Large heading above the photo grid.",
    type: "string",
  }),
  defineField({
    name: "galleryIntro",
    title: "Gallery intro",
    description: "Short paragraph beside the Gallery heading.",
    type: "text",
  }),
  defineField({
    name: "whyKicker",
    title: "Why Celestia label",
    description: "Small label above the Why Celestia section.",
    type: "string",
  }),
  defineField({
    name: "whyHeading",
    title: "Why Celestia heading",
    description: "Large heading in the Why Celestia section.",
    type: "string",
  }),
  defineField({
    name: "whyIntro",
    title: "Why Celestia intro",
    description: "Paragraph under the Why Celestia heading.",
    type: "text",
  }),
  defineField({
    name: "inquiryKicker",
    title: "Inquiry label",
    description: "Small label above the inquiry form copy.",
    type: "string",
  }),
  defineField({
    name: "inquiryHeading",
    title: "Inquiry heading",
    description: "Large heading beside the inquiry form.",
    type: "string",
  }),
  defineField({
    name: "inquiryIntro",
    title: "Inquiry intro",
    description: "Paragraph beside the inquiry form.",
    type: "text",
  }),
  defineField({
    name: "footerBackToTop",
    title: "Footer back-to-top label",
    description: "Text beside the heart icon in the footer.",
    type: "string",
  }),
];

export const schemaTypes = [
  defineType({
    name: "siteSettings",
    title: "Site Settings",
    type: "document",
    groups: [
      { name: "brand", title: "Brand & Contact", default: true },
      { name: "stats", title: "Hero Stats" },
      { name: "sections", title: "Section Headings" },
      { name: "why", title: "Why Celestia" },
    ],
    fields: [
      defineField({
        name: "brandName",
        title: "Brand name",
        description: "Appears in the header logo area and footer.",
        type: "string",
        group: "brand",
      }),
      defineField({
        name: "descriptor",
        title: "Brand descriptor",
        description: "Small text under the Celestia name in the header and footer.",
        type: "string",
        group: "brand",
      }),
      defineField({
        name: "tagline",
        title: "Footer tagline",
        description: "Short line in the footer.",
        type: "string",
        group: "brand",
      }),
      defineField({
        name: "facebookUrl",
        title: "Facebook URL",
        description: "Used by the Message buttons and Facebook Page link.",
        type: "url",
        group: "brand",
      }),
      defineField({
        name: "phone",
        title: "Display phone number",
        description: "Shown in the contact links and inquiry section.",
        type: "string",
        group: "brand",
      }),
      defineField({
        name: "phoneHref",
        title: "Phone link value",
        description: "Used by phone/SMS links. Use country code, for example +639477703209.",
        type: "string",
        group: "brand",
      }),
      defineField({
        name: "locationLabel",
        title: "Hero location label",
        description: "Small location text above the hero headline.",
        type: "string",
        group: "brand",
      }),
      defineField({
        name: "stats",
        title: "Hero stats",
        description: "The three small stat blocks under the hero buttons. Clear the list to use defaults.",
        type: "array",
        group: "stats",
        of: [
          defineArrayMember({
            type: "object",
            fields: [
              defineField({
                name: "value",
                title: "Large stat value",
                description: "Example: 1K+, 7, PH.",
                type: "string",
              }),
              defineField({
                name: "label",
                title: "Small stat label",
                description: "Example: Facebook followers.",
                type: "string",
              }),
            ],
            preview: {
              select: { title: "value", subtitle: "label" },
            },
          }),
        ],
      }),
      defineField({
        name: "sections",
        title: "Website section headings",
        description: "Controls labels, headings, and intro paragraphs across the page. Clear any field to use the default.",
        type: "object",
        group: "sections",
        fields: sectionFields,
      }),
      defineField({
        name: "whyPoints",
        title: "Why Celestia bullet points",
        description: "The checklist-style points beside the Why Celestia copy. Clear the list to use defaults.",
        type: "array",
        group: "why",
        of: [defineArrayMember({ type: "string" })],
      }),
    ],
    preview: {
      select: { title: "brandName", subtitle: "tagline" },
    },
  }),
  defineType({
    name: "hero",
    title: "Hero",
    type: "document",
    groups: [
      { name: "copy", title: "Hero Copy", default: true },
      { name: "images", title: "Hero Images" },
    ],
    fields: [
      defineField({
        name: "headline",
        title: "Main hero headline",
        description: "Largest text in the first screen.",
        type: "string",
        group: "copy",
      }),
      defineField({
        name: "lede",
        title: "Hero intro paragraph",
        description: "Paragraph under the main headline.",
        type: "text",
        group: "copy",
      }),
      defineField({
        name: "primaryCtaLabel",
        title: "Primary button label",
        description: "Text on the dark Facebook message button.",
        type: "string",
        group: "copy",
      }),
      defineField({
        name: "secondaryCtaLabel",
        title: "Secondary button label",
        description: "Text on the Request Package button.",
        type: "string",
        group: "copy",
      }),
      defineField({
        name: "note",
        title: "Hero image note",
        description: "Small floating note over the hero image collage.",
        type: "string",
        group: "copy",
      }),
      defineField({
        name: "mainImage",
        title: "Main hero image",
        description: "Large image on the right side of the first screen.",
        type: "image",
        options: { hotspot: true },
        group: "images",
        fields: [
          defineField({
            name: "alt",
            title: "Alt text",
            description: "Describe the main hero image for accessibility.",
            type: "string",
          }),
        ],
      }),
      defineField({
        name: "sideImage",
        title: "Small overlapping hero image",
        description: "Smaller image layered over the main hero image.",
        type: "image",
        options: { hotspot: true },
        group: "images",
        fields: [
          defineField({
            name: "alt",
            title: "Alt text",
            description: "Describe the small hero image for accessibility.",
            type: "string",
          }),
        ],
      }),
    ],
    preview: { select: { title: "headline", media: "mainImage" } },
  }),
  defineType({
    name: "eventType",
    title: "Event Type",
    type: "document",
    fields: [
      defineField({
        name: "title",
        title: "Event card title",
        description: "Appears as a card title in the Events section.",
        type: "string",
      }),
      defineField({
        name: "accent",
        title: "Card number",
        description: "Large pale number shown at the top of the event card.",
        type: "string",
      }),
      defineField({
        name: "copy",
        title: "Card description",
        description: "Short paragraph inside the event card.",
        type: "text",
      }),
      defineField({
        name: "order",
        title: "Display order",
        description: "Lower numbers appear first.",
        type: "number",
        initialValue: 10,
      }),
    ],
    preview: { select: { title: "title", subtitle: "copy" } },
  }),
  defineType({
    name: "serviceOffer",
    title: "Service / Offer",
    type: "document",
    fields: [
      defineField({
        name: "title",
        title: "Service card title",
        description: "Appears in the Offers section and inquiry checkboxes.",
        type: "string",
      }),
      defineField({
        name: "icon",
        title: "Service icon",
        description: "Controls the small icon inside this service card.",
        type: "string",
        options: {
          list: [
            { title: "Coffee", value: "coffee" },
            { title: "Cocktail", value: "cocktail" },
            { title: "Grazing", value: "grazing" },
            { title: "Food cart", value: "cart" },
            { title: "Perfume", value: "perfume" },
            { title: "Selfie mirror", value: "mirror" },
            { title: "Event planner", value: "planner" },
          ],
          layout: "radio",
        },
      }),
      defineField({
        name: "description",
        title: "Service card description",
        description: "Short paragraph inside this service card.",
        type: "text",
      }),
      imageWithAlt,
      defineField({
        name: "order",
        title: "Display order",
        description: "Lower numbers appear first.",
        type: "number",
        initialValue: 10,
      }),
    ],
    preview: { select: { title: "title", subtitle: "description", media: "image" } },
  }),
  defineType({
    name: "featuredPackage",
    title: "Featured Package",
    type: "document",
    fields: [
      defineField({
        name: "name",
        title: "Package card title",
        description: "Appears as the package name in the dark Featured Packages section.",
        type: "string",
      }),
      defineField({
        name: "idealFor",
        title: "Ideal-for line",
        description: "Small paragraph above the package name.",
        type: "text",
      }),
      defineField({
        name: "includes",
        title: "Included items",
        description: "Checklist items inside the package card. Clear the list to use defaults.",
        type: "array",
        of: [defineArrayMember({ type: "string" })],
      }),
      defineField({
        name: "order",
        title: "Display order",
        description: "Lower numbers appear first.",
        type: "number",
        initialValue: 10,
      }),
    ],
    preview: { select: { title: "name", subtitle: "idealFor" } },
  }),
  defineType({
    name: "galleryImage",
    title: "Gallery Image",
    type: "document",
    fields: [
      defineField({
        name: "category",
        title: "Gallery pill label",
        description: "Small label overlaid at the bottom of the gallery photo.",
        type: "string",
      }),
      defineField({
        name: "alt",
        title: "Alt text",
        description: "Describe the gallery photo for accessibility and SEO.",
        type: "string",
      }),
      defineField({
        name: "image",
        title: "Gallery photo",
        description: "Photo shown in the Gallery grid.",
        type: "image",
        options: { hotspot: true },
      }),
      defineField({
        name: "order",
        title: "Display order",
        description: "Lower numbers appear first.",
        type: "number",
        initialValue: 10,
      }),
    ],
    preview: { select: { title: "category", subtitle: "alt", media: "image" } },
  }),
];
